version: "3"

services:
    delphi:
        image: delphi:1.1.0
        build:
            context: ./src
        restart: unless-stopped
        volumes:
            - ./docs:/app/docs
        ports:
            - 8091:8501
        networks:
            - chroma_net
        environment:
          - OPENAI_API_KEY=
          - CHROMA_ADDR=
          - CHROMA_PORT=
          - APP_NAME=
          - CREDENTIALS_FILE=
          - BOT_IMAGE=https://i.pinimg.com/originals/02/c5/a8/02c5a82909a225411008d772ee6b7d62.png
networks:
  chroma_net:
    external: true
    name: chroma_net